---

- name: Check if Firewalld Service Exists
  command: systemctl status firewalld
  ignore_errors: yes
  changed_when: false
  register: service_firewalld_status

- name: Configuration Terraira Firewall service
  synchronize: src=../files/ dest=/
  when: service_firewalld_status | succeeded

- name: Add Terrraria zone
  shell: "firewall-cmd --zone=public --permanent --add-service=terraria"
  when: service_firewalld_status | succeeded

- name: Reload configuration Firewalld
  shell: "firewall-cmd --reload"
  when: service_firewalld_status | succeeded
